AllCops:
  RunRailsCops: true
  Include:
    - 'Rakefile'
    - 'codeship-*.rb'
    - 'config.ru'
    - 'Gemfile'
  Exclude:
    - 'bin/*'
    - 'app/helpers/sql_helper.rb'
Rails/HasAndBelongsToMany:
  Enabled: false
Documentation:
  Enabled: false