AllCops:
  RunRailsCops: true
  Include:
    - 'Rakefile'
    - 'codeship-*.rb'
    - 'config.ru'
    - 'Gemfile'
    - 'lib/tasks/*.rake'
  Exclude:
    - 'bin/*'
    - 'app/helpers/sql_helper.rb'
    - 'lib/tasks/dev.rake'
Rails/HasAndBelongsToMany:
  Enabled: false
Documentation:
  Enabled: false