AllCops:
  RunRailsCops: true
  Include:
    - 'Rakefile'
    - 'codeship-*.rb'
    - 'config.ru'
    - 'Gemfile'
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/data/20150829160525_nba2016.rb'
Rails/HasAndBelongsToMany:
  Enabled: false
Documentation:
  Enabled: false