# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07e7e292599532cdc72becabc4692037176a1861d3fc55b5b86faf3e677bfb3c5425f5564d7cd1a4a0dfa72191430902733c384f1f1f94d720b2bb439bd988a4

test:
  secret_key_base: 09358503f77c100a3f0928877fdb18a19e8e70ca70f24236580ca15079c0af8250488d1f9ec1b8470b415bd16950eb4b4e48345b98635f338e1a564966a21223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
